#!/bin/sh
#
# Starts james.
#

start() {
	echo -n "Starting james: "
	start-stop-daemon -S -q -p /var/run/james.pid --exec /usr/bin/james
	echo "OK"
}
stop() {
	echo -n "Stopping james: "
	start-stop-daemon -K -q -p /var/run/james.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

