#!/bin/sh
#
# Starts hostapd.
#

start() {
	echo -n "Starting hostapd: "
	start-stop-daemon -S -q -p /var/run/hostapd.pid --exec /usr/sbin/hostapd -- /etc/hostapd/hostapd.conf
	echo "OK"
}
stop() {
	echo -n "Stopping hostapd: "
	start-stop-daemon -K -q -p /var/run/hostapd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

